org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Minecraft target
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
java_version=17
loader_version=0.19.3

# Required and optional mods
fabric_api_version=0.92.11+1.20.1
fabric_api_version_id=xhLT3C5f
litematica_version=0.15.4
litematica_version_id=1ZTpW1lr
malilib_version=0.16.3
malilib_next_version=0.17.0
malilib_version_id=V7yLDtJV
modmenu_version=7.2.2
modmenu_version_id=lEkperf6
chisels_bits_version=20.1.20
chisels_bits_file_id=7620766

# Exact Modrinth files embedded in the generated mrpack index
fabric_api_file_name=fabric-api-0.92.11+1.20.1.jar
fabric_api_sha512=fb8d9d5c5ee387b12770fcef1cb4327f1575bd21606f1a268c9eff43fd3697cf0a3af55dd688cdc913f1423737f8905e13282eb69dd69f0995c32d6e620efb3f
fabric_api_download_url=https://cdn.modrinth.com/data/P7dR8mSH/versions/xhLT3C5f/fabric-api-0.92.11%2B1.20.1.jar
fabric_api_file_size=2137144
litematica_file_name=litematica-fabric-1.20.1-0.15.4.jar
litematica_sha512=3cf1f2a16997e5a1dcda37b2626595f37873a39e33c254af1a7eda986aa13be74449d56fe706db7f158ed1a047271a48fa705091e5c71e3b0aa28d0d53c7cb01
litematica_download_url=https://cdn.modrinth.com/data/bEpr0Arc/versions/1ZTpW1lr/litematica-fabric-1.20.1-0.15.4.jar
litematica_file_size=923876
malilib_file_name=malilib-fabric-1.20.1-0.16.3.jar
malilib_sha512=2c16a64cf9af03569618c6bd0359797bbaecec854ac8e8197e9180b1739eb74b6157a9c389a4f8dd8b4aabe52227aafb8d2a6b6b72732ed3c450ff9a0849234c
malilib_download_url=https://cdn.modrinth.com/data/GcWjdA9I/versions/V7yLDtJV/malilib-fabric-1.20.1-0.16.3.jar
malilib_file_size=545403
modmenu_file_name=modmenu-7.2.2.jar
modmenu_sha512=9a7837e04bb34376611b207a3b20e5fe1c82a4822b42929d5b410809ec4b88ff3cac8821c4568f880775bafa3c079dfc7800f8471356a4046248b12607e855eb
modmenu_download_url=https://cdn.modrinth.com/data/mOgUt4GM/versions/lEkperf6/modmenu-7.2.2.jar
modmenu_file_size=721366

# Project identity
mod_version=0.5.2
maven_group=io.github.yromko
archives_base_name=minesplat-fabric
