package io.github.yromko.minesplat.litematica;

import fi.dy.masa.litematica.data.DataManager;
import fi.dy.masa.litematica.data.SchematicHolder;
import fi.dy.masa.litematica.schematic.LitematicaSchematic;
import fi.dy.masa.litematica.schematic.SchematicMetadata;
import fi.dy.masa.litematica.schematic.container.LitematicaBlockStateContainer;
import fi.dy.masa.litematica.schematic.placement.SchematicPlacement;
import fi.dy.masa.litematica.schematic.placement.SchematicPlacementManager;
import fi.dy.masa.litematica.selection.AreaSelection;
import fi.dy.masa.litematica.selection.Box;
import io.github.yromko.minesplat.palette.MatchedVoxels;
import io.github.yromko.minesplat.palette.PaletteEntry;
import io.github.yromko.minesplat.util.FileNames;
import io.github.yromko.minesplat.workflow.GenerationState;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.registry.Registries;
import net.minecraft.state.property.Property;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.Vec3i;
import net.minecraft.client.MinecraftClient;

import java.nio.file.Path;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.function.Consumer;

public final class LitematicaBridge implements SchematicExporter {
    private static final String REGION_NAME = "minesplat";

    private final MinecraftClient client;
    private final Executor ioExecutor;

    public LitematicaBridge(MinecraftClient client, Executor ioExecutor) {
        this.client = client;
        this.ioExecutor = ioExecutor;
    }

    @Override
    public CompletableFuture<Path> saveAndPlace(
            String requestedName,
            int resolution,
            MatchedVoxels voxels,
            Consumer<GenerationState> stateConsumer
    ) {
        CompletableFuture<PreparedSchematic> prepared = onClientThread(
                () -> prepare(requestedName, resolution, voxels));
        return prepared.thenCompose(value -> {
            stateConsumer.accept(GenerationState.SAVING);
            return CompletableFuture.supplyAsync(() -> save(value), ioExecutor);
        }).thenCompose(saved -> {
            stateConsumer.accept(GenerationState.PLACING);
            return onClientThread(() -> place(saved));
        });
    }

    private PreparedSchematic prepare(
            String requestedName,
            int resolution,
            MatchedVoxels voxels
    ) {
        requireWorld();
        try {
            Path directory = FabricLoader.getInstance().getGameDir()
                    .resolve("schematics")
                    .resolve("minesplat");
            Path output = FileNames.uniqueSchematicPath(directory, requestedName, resolution);
            String displayName = FileNames.sanitize(requestedName);

            AreaSelection selection = new AreaSelection();
            selection.setName(displayName);
            selection.setExplicitOrigin(BlockPos.ORIGIN);
            selection.addSubRegionBox(new Box(
                    BlockPos.ORIGIN,
                    new BlockPos(voxels.width() - 1, voxels.height() - 1, voxels.depth() - 1),
                    REGION_NAME), true);

            LitematicaSchematic schematic =
                    LitematicaSchematic.createEmptySchematic(selection, displayName);
            if (schematic == null) {
                throw new IllegalStateException("Litematica could not create an empty schematic");
            }
            LitematicaBlockStateContainer container =
                    schematic.getSubRegionContainer(REGION_NAME);
            if (container == null) {
                throw new IllegalStateException("Litematica did not create the MineSplat region");
            }

            Map<String, BlockState> states = new HashMap<>();
            for (int index = 0; index < voxels.size(); index++) {
                PaletteEntry entry = voxels.block(index);
                BlockState state = states.computeIfAbsent(entry.stateKey(), unused -> resolve(entry));
                container.set(voxels.x(index), voxels.y(index), voxels.z(index), state);
            }

            SchematicMetadata metadata = schematic.getMetadata();
            long now = Instant.now().toEpochMilli();
            metadata.setName(displayName);
            metadata.setAuthor(client.getSession().getUsername());
            metadata.setDescription("Generated by MineSplat from TripoSplat TSVOX v2");
            metadata.setRegionCount(1);
            metadata.setTotalBlocks(voxels.size());
            metadata.setTotalVolume(Math.multiplyExact(
                    Math.multiplyExact(voxels.width(), voxels.height()), voxels.depth()));
            metadata.setEnclosingSize(new Vec3i(voxels.width(), voxels.height(), voxels.depth()));
            metadata.setTimeCreated(now);
            metadata.setTimeModified(now);
            return new PreparedSchematic(schematic, output, displayName, voxels.width(), voxels.depth());
        } catch (RuntimeException exception) {
            throw exception;
        } catch (Exception exception) {
            throw new IllegalStateException("Cannot prepare Litematica schematic", exception);
        }
    }

    private SavedSchematic save(PreparedSchematic prepared) {
        Path directory = prepared.output().getParent();
        String fileName = prepared.output().getFileName().toString();
        if (!prepared.schematic().writeToFile(directory, fileName, false)) {
            throw new IllegalStateException("Litematica could not save " + prepared.output());
        }
        return new SavedSchematic(
                prepared.output(), prepared.displayName(), prepared.width(), prepared.depth());
    }

    private Path place(SavedSchematic saved) {
        requireWorld();
        LitematicaSchematic schematic = SchematicHolder.getInstance()
                .getOrLoad(saved.output());
        if (schematic == null) {
            throw new IllegalStateException("Litematica could not load the saved schematic");
        }

        Vec3d look = client.player.getRotationVec(1.0f);
        double horizontalLength = Math.hypot(look.x, look.z);
        double lookX = horizontalLength > 1.0e-6 ? look.x / horizontalLength : 0;
        double lookZ = horizontalLength > 1.0e-6 ? look.z / horizontalLength : 1;
        double distance = Math.max(saved.width(), saved.depth()) / 2.0 + 4.0;
        BlockPos player = client.player.getBlockPos();
        BlockPos origin = new BlockPos(
                (int) Math.floor(player.getX() + lookX * distance - saved.width() / 2.0),
                player.getY(),
                (int) Math.floor(player.getZ() + lookZ * distance - saved.depth() / 2.0));

        SchematicPlacement placement = SchematicPlacement.createFor(
                schematic, origin, saved.displayName(), true, true);
        SchematicPlacementManager manager = DataManager.getSchematicPlacementManager();
        manager.addSchematicPlacement(placement, true);
        manager.setSelectedSchematicPlacement(placement);
        return saved.output();
    }

    private BlockState resolve(PaletteEntry entry) {
        Identifier id = Identifier.tryParse(entry.blockId());
        if (id == null || !Registries.BLOCK.containsId(id)) {
            throw new IllegalArgumentException("Unknown Minecraft block " + entry.blockId());
        }
        Block block = Registries.BLOCK.get(id);
        BlockState state = block.getDefaultState();
        for (Map.Entry<String, String> requested : entry.properties().entrySet()) {
            Property<?> property = block.getStateManager().getProperty(requested.getKey());
            if (property == null) {
                throw new IllegalArgumentException(
                        "Block " + entry.blockId() + " has no property " + requested.getKey());
            }
            state = withParsedProperty(state, property, requested.getValue(), entry.blockId());
        }
        return state;
    }

    private static <T extends Comparable<T>> BlockState withParsedProperty(
            BlockState state,
            Property<T> property,
            String value,
            String blockId
    ) {
        Optional<T> parsed = property.parse(value);
        if (parsed.isEmpty()) {
            throw new IllegalArgumentException(
                    "Invalid " + property.getName() + "=" + value + " for " + blockId);
        }
        return state.with(property, parsed.get());
    }

    private void requireWorld() {
        if (client.world == null || client.player == null) {
            throw new IllegalStateException("Open a Minecraft world before creating a schematic");
        }
    }

    private <T> CompletableFuture<T> onClientThread(ThrowingSupplier<T> supplier) {
        CompletableFuture<T> future = new CompletableFuture<>();
        client.execute(() -> {
            try {
                future.complete(supplier.get());
            } catch (Throwable throwable) {
                future.completeExceptionally(throwable);
            }
        });
        return future;
    }

    @FunctionalInterface
    private interface ThrowingSupplier<T> {
        T get() throws Exception;
    }

    private record PreparedSchematic(
            LitematicaSchematic schematic,
            Path output,
            String displayName,
            int width,
            int depth
    ) {
    }

    private record SavedSchematic(
            Path output,
            String displayName,
            int width,
            int depth
    ) {
    }
}
